import { describe, expect, it } from "vitest";
import {
  renderAliasMap,
  renderAppTreeModule,
  renderDtsShim,
  renderRuntimeModule,
  virtualIdFor,
} from "./render";

describe("virtualIdFor", () => {
  it("maps the empty route key to _root", () => {
    expect(virtualIdFor("")).toBe("virtual:react-router-next/_root");
  });

  it("preserves the route key for non-empty keys", () => {
    expect(virtualIdFor("posts/[id]")).toBe(
      "virtual:react-router-next/posts/[id]",
    );
  });
});

describe("renderRuntimeModule", () => {
  it("emits only generate() for a static route", () => {
    const source = renderRuntimeModule("about");
    expect(source).toContain('const PATH = "about";');
    expect(source).toContain("export function generate()");
    expect(source).toContain("generateBase(PATH, {})");
    expect(source).not.toContain("useRouteParams");
  });

  it("emits generate(params) and useRouteParams for a dynamic route", () => {
    const source = renderRuntimeModule("posts/[id]");
    expect(source).toContain('const PATH = "posts/[id]";');
    expect(source).toContain("export function useRouteParams()");
    expect(source).toContain("useRouteParamsBase(PATH)");
    expect(source).toContain("export function generate(params)");
    expect(source).toContain("generateBase(PATH, params)");
  });

  it("JSON-encodes the route key so special characters stay quoted", () => {
    const key = 'foo"bar';
    const source = renderRuntimeModule(key);
    expect(source).toContain(`const PATH = ${JSON.stringify(key)};`);
  });

  it("emits byte-identical output for a static route with no schema", () => {
    expect(renderRuntimeModule("about"))
      .toBe(`// AUTO-GENERATED by react-router-next — do not edit.
import { generate as generateBase } from "@evolonix/react-router-next";

const PATH = "about";

export function generate() {
  return generateBase(PATH, {});
}
`);
  });

  it("emits byte-identical output for a dynamic route with no schema", () => {
    expect(renderRuntimeModule("posts/[id]"))
      .toBe(`// AUTO-GENERATED by react-router-next — do not edit.
import {
  generate as generateBase,
  useRouteParams as useRouteParamsBase,
} from "@evolonix/react-router-next";

const PATH = "posts/[id]";

export function useRouteParams() {
  return useRouteParamsBase(PATH);
}

export function generate(params) {
  return generateBase(PATH, params);
}
`);
  });

  it("wires up searchParams for a static route with a schema", () => {
    const source = renderRuntimeModule("posts", "/src/app/posts/page.tsx");
    expect(source).toContain(
      'import { searchSchema as schema } from "/src/app/posts/page.tsx";',
    );
    expect(source).toContain("useSearchParams as useSearchParamsBase");
    expect(source).toContain("export { schema as searchSchema };");
    expect(source).not.toContain("export const searchSchema = schema;");
    expect(source).toContain("return useSearchParamsBase(PATH, schema);");
    expect(source).toContain("export function generate(opts)");
    expect(source).toContain("generateBase(PATH, {}, opts)");
    expect(source).not.toContain("useRouteParams");
  });

  it("wires up params and searchParams together", () => {
    const source = renderRuntimeModule(
      "posts/[id]",
      "../../src/app/posts/[id]/page.tsx",
    );
    expect(source).toContain("useRouteParams as useRouteParamsBase");
    expect(source).toContain("useSearchParams as useSearchParamsBase");
    expect(source).toContain("export function useRouteParams()");
    expect(source).toContain("export function generate(params, opts)");
    expect(source).toContain("generateBase(PATH, params, opts)");
  });
});

describe("renderDtsShim", () => {
  it("always emits the app-tree ambient declaration", () => {
    const shim = renderDtsShim([]);
    expect(shim).toContain(
      'declare module "virtual:react-router-next/app-tree"',
    );
    expect(shim).toContain("export const modules: Record<string, RouteModule>");
  });

  it("emits one declare module block per route key", () => {
    const shim = renderDtsShim(["", "posts/[id]"]);
    expect(shim).toContain('declare module "virtual:react-router-next/_root"');
    expect(shim).toContain(
      'declare module "virtual:react-router-next/posts/[id]"',
    );
  });

  it("omits useRouteParams for routes without params but still emits RouteProps", () => {
    const shim = renderDtsShim([""]);
    const rootBlockMatch = shim.match(
      /declare module "virtual:react-router-next\/_root"[\s\S]*?\n}\n/,
    );
    expect(rootBlockMatch).not.toBeNull();
    const block = rootBlockMatch![0];
    expect(block).toContain("export function generate(): string;");
    expect(block).not.toContain("useRouteParams");
    // Every route's page receives `params` + `searchParams` (untyped here).
    expect(block).toContain(
      "export type RouteProps = { params: RouteParams; searchParams: SearchParamsRecord };",
    );
  });

  it("emits useRouteParams and RouteProps for dynamic routes", () => {
    const shim = renderDtsShim(["posts/[id]"]);
    expect(shim).toContain("export function useRouteParams(): RouteParams;");
    expect(shim).toContain(
      "export type RouteProps = { params: RouteParams; searchParams: SearchParamsRecord };",
    );
    expect(shim).toContain(
      "export function generate(params: RouteParams): string;",
    );
  });

  it("produces deterministic output for a given input order", () => {
    const a = renderDtsShim(["a", "b", "c"]);
    const b = renderDtsShim(["a", "b", "c"]);
    expect(a).toBe(b);
  });

  it("emits search-aware types for a route with a schema specifier", () => {
    const shim = renderDtsShim(
      ["posts"],
      new Map([["posts", "../../src/app/posts/page"]]),
    );
    expect(shim).toContain(
      'import type { StandardSchemaV1 } from "@standard-schema/spec";',
    );
    expect(shim).toContain(
      'import type { searchSchema as SearchSchema } from "../../src/app/posts/page";',
    );
    expect(shim).toContain(
      "export type SearchParams = StandardSchemaV1.InferOutput<typeof SearchSchema>;",
    );
    expect(shim).toContain("export const searchSchema: typeof SearchSchema;");
    // RouteProps.searchParams is the validated schema output for schema routes.
    expect(shim).toContain(
      "export type RouteProps = { params: RouteParams; searchParams: SearchParams };",
    );
    expect(shim).toContain(
      "export function useSearchParams(): readonly [SearchParams, (next: SearchParams, opts?: SetSearchOptions) => void];",
    );
    expect(shim).toContain(", SetSearchOptions } from");
    expect(shim).toContain(
      "export function generate(opts?: { search?: SearchParams }): string;",
    );
  });

  it("threads params alongside search in the generate signature", () => {
    const shim = renderDtsShim(
      ["posts/[id]"],
      new Map([["posts/[id]", "../../src/app/posts/[id]/page"]]),
    );
    expect(shim).toContain(
      "export function generate(params: RouteParams, opts?: { search?: SearchParams }): string;",
    );
    expect(shim).toContain("export function useRouteParams(): RouteParams;");
  });

  it("leaves routes absent from the specifier map unchanged", () => {
    const withMap = renderDtsShim(["about"], new Map([["posts", "./x"]]));
    const without = renderDtsShim(["about"]);
    expect(withMap).toBe(without);
  });
});

describe("renderAppTreeModule", () => {
  it("emits an empty modules map when no entries are provided", () => {
    const source = renderAppTreeModule({
      appDirRootRelative: "/src/app",
      entries: [],
    });
    expect(source).toContain("export const modules = {");
    expect(source).toContain('export const appDir = "/src/app";');
    expect(source).not.toContain("import * as");
  });

  it("emits one static import per entry, keyed by the module key", () => {
    const source = renderAppTreeModule({
      appDirRootRelative: "/src/app",
      entries: [
        {
          importSpecifier: "../../src/app/page.tsx",
          moduleKey: "/src/app/page.tsx",
        },
        {
          importSpecifier: "../../src/app/posts/[id]/page.tsx",
          moduleKey: "/src/app/posts/[id]/page.tsx",
        },
      ],
    });
    expect(source).toContain('import * as m0 from "../../src/app/page.tsx";');
    expect(source).toContain(
      'import * as m1 from "../../src/app/posts/[id]/page.tsx";',
    );
    expect(source).toContain('["/src/app/page.tsx"]: m0,');
    expect(source).toContain('["/src/app/posts/[id]/page.tsx"]: m1,');
  });
});

describe("renderAliasMap", () => {
  it("emits an exact-match alias for app-tree and a prefix alias for routes", () => {
    const raw = renderAliasMap({ outDir: "/abs/out" });
    const parsed = JSON.parse(raw) as Record<string, string>;
    expect(parsed["virtual:react-router-next/app-tree$"]).toBe(
      "/abs/out/app-tree.js",
    );
    expect(parsed["virtual:react-router-next"]).toBe("/abs/out/routes");
  });

  it("terminates the JSON document with a trailing newline", () => {
    const raw = renderAliasMap({ outDir: "/abs/out" });
    expect(raw.endsWith("\n")).toBe(true);
  });
});
