import { routeHasParams } from "./scan";

const HEADER = "// AUTO-GENERATED by react-router-next — do not edit.";

/**
 * Source emitted into the **runtime** virtual module for a given route key.
 * Plain JavaScript — type info lives in the ambient `.d.ts` shim emitted by
 * `renderDtsShim`. Virtual modules aren't transformed as TypeScript by Vite,
 * so the runtime form must not contain type-only syntax.
 *
 * When `searchSpecifier` is given (the route's leaf file exports a
 * `searchParams` schema), the module also imports that schema, re-exports it,
 * and wires up `useSearchParams`. Routes without a schema emit the original
 * output unchanged.
 */
export function renderRuntimeModule(
  routeKey: string,
  searchSpecifier?: string,
): string {
  const hasParams = routeHasParams(routeKey);

  if (!searchSpecifier) {
    if (!hasParams) {
      return `${HEADER}
import { generate as generateBase } from "@evolonix/react-router-next";

const PATH = ${JSON.stringify(routeKey)};

export function generate() {
  return generateBase(PATH, {});
}
`;
    }

    return `${HEADER}
import {
  generate as generateBase,
  useRouteParams as useRouteParamsBase,
} from "@evolonix/react-router-next";

const PATH = ${JSON.stringify(routeKey)};

export function useRouteParams() {
  return useRouteParamsBase(PATH);
}

export function generate(params) {
  return generateBase(PATH, params);
}
`;
  }

  const named = ["generate as generateBase"];
  if (hasParams) named.push("useRouteParams as useRouteParamsBase");
  named.push("useSearchParams as useSearchParamsBase");

  const routeParamsFn = hasParams
    ? `
export function useRouteParams() {
  return useRouteParamsBase(PATH);
}
`
    : "";

  const generateFn = hasParams
    ? `export function generate(params, opts) {
  return generateBase(PATH, params, opts);
}`
    : `export function generate(opts) {
  return generateBase(PATH, {}, opts);
}`;

  return `${HEADER}
import {
${named.map((n) => `  ${n},`).join("\n")}
} from "@evolonix/react-router-next";
import { searchSchema as schema } from ${JSON.stringify(searchSpecifier)};

const PATH = ${JSON.stringify(routeKey)};

// A live-binding re-export, not \`export const searchSchema = schema\` — a page
// may import its own route's \`useSearchParams\`/\`generate\` from this module,
// making the two modules circular. An eager read of \`schema\` at init time would
// hit the page's still-uninitialized \`searchSchema\` const (TDZ). The functions
// below read \`schema\` lazily, at render, by which point the page is initialized.
export { schema as searchSchema };
${routeParamsFn}
export function useSearchParams() {
  return useSearchParamsBase(PATH, schema);
}

${generateFn}
`;
}

/**
 * Body of a `declare module 'virtual:react-router-next/<route-key>' { ... }`
 * block. Same shape as the runtime module, but with type-only declarations so
 * `tsc` and editors resolve consumer imports without spinning up Vite.
 *
 * Every route gets `RouteProps` (a page always receives `params` +
 * `searchParams`, mirroring Next). When the route declares a `searchSchema`,
 * `searchParams` is the validated schema output and the module also exposes
 * `useSearchParams`, the schema, and a `search` option on `generate`; otherwise
 * `searchParams` is the untyped `SearchParamsRecord`.
 *
 * `searchDtsSpecifier` is an **extensionless** module specifier (relative to
 * the d.ts location) pointing at the route's leaf file — present only when that
 * file exports a `searchSchema`. Extensionless so it resolves under a
 * consumer's `moduleResolution: "bundler"` without needing
 * `allowImportingTsExtensions`.
 */
function renderDeclareBody(
  routeKey: string,
  searchDtsSpecifier?: string,
): string {
  const hasParams = routeHasParams(routeKey);
  const hasSchema = Boolean(searchDtsSpecifier);

  const lines: string[] = [];
  if (hasSchema) {
    lines.push(
      `  import type { StandardSchemaV1 } from "@standard-schema/spec";`,
      `  import type { searchSchema as SearchSchema } from ${JSON.stringify(searchDtsSpecifier)};`,
    );
  }
  const pkgTypes = hasSchema
    ? "RouteParams as RouteParamsBase, SearchParamsRecord, SetSearchOptions"
    : "RouteParams as RouteParamsBase, SearchParamsRecord";
  lines.push(
    `  import type { ${pkgTypes} } from "@evolonix/react-router-next";`,
    `  const PATH: ${JSON.stringify(routeKey)};`,
    `  export type RouteParams = RouteParamsBase<typeof PATH>;`,
  );
  if (hasSchema) {
    lines.push(
      `  export type SearchParams = StandardSchemaV1.InferOutput<typeof SearchSchema>;`,
    );
  }
  const searchPropType = hasSchema ? "SearchParams" : "SearchParamsRecord";
  lines.push(
    `  export type RouteProps = { params: RouteParams; searchParams: ${searchPropType} };`,
  );
  if (hasSchema) {
    lines.push(`  export const searchSchema: typeof SearchSchema;`);
  }
  if (hasParams) {
    lines.push(`  export function useRouteParams(): RouteParams;`);
  }
  if (hasSchema) {
    lines.push(
      `  export function useSearchParams(): readonly [SearchParams, (next: SearchParams, opts?: SetSearchOptions) => void];`,
    );
  }

  const paramsArg = hasParams ? "params: RouteParams" : "";
  const searchArg = hasSchema ? "opts?: { search?: SearchParams }" : "";
  const generateArgs = [paramsArg, searchArg].filter(Boolean).join(", ");
  lines.push(`  export function generate(${generateArgs}): string;`);

  return lines.join("\n") + "\n";
}

export function virtualIdFor(routeKey: string): string {
  return `virtual:react-router-next/${routeKey === "" ? "_root" : routeKey}`;
}

export type AppTreeEntry = {
  /** Import specifier emitted for this route file — already resolved relative
   *  to the codegen output directory (e.g. "../../src/app/page.tsx"). */
  importSpecifier: string;
  /** Object key in the emitted `modules` map — root-relative, matching the
   *  shape the Vite plugin produces (e.g. "/src/app/page.tsx"). */
  moduleKey: string;
};

/**
 * Source emitted for the codegen replacement of
 * `virtual:react-router-next/app-tree`. Statically imports every route file so
 * any bundler (webpack/Rspack/Rollup/esbuild) can resolve it — no
 * `import.meta.glob` dependency.
 */
export function renderAppTreeModule(opts: {
  appDirRootRelative: string;
  entries: readonly AppTreeEntry[];
}): string {
  const { appDirRootRelative, entries } = opts;
  const imports = entries
    .map(
      (entry, i) =>
        `import * as m${i} from ${JSON.stringify(entry.importSpecifier)};`,
    )
    .join("\n");
  const mapEntries = entries
    .map((entry, i) => `  [${JSON.stringify(entry.moduleKey)}]: m${i},`)
    .join("\n");
  return `${HEADER}
${imports}

export const modules = {
${mapEntries}
};
export const appDir = ${JSON.stringify(appDirRootRelative)};
`;
}

/**
 * Webpack/Rspack-shaped `resolve.alias` map that routes
 * `virtual:react-router-next/...` requests to the codegen output. The `$`
 * suffix on the app-tree key is webpack's "exact match only" marker, so
 * `virtual:react-router-next/app-tree` resolves to `app-tree.js` and every
 * other `virtual:react-router-next/<key>` falls through to the prefix alias.
 */
export function renderAliasMap(opts: { outDir: string }): string {
  const map = {
    "virtual:react-router-next/app-tree$": `${opts.outDir}/app-tree.js`,
    "virtual:react-router-next": `${opts.outDir}/routes`,
  };
  return `${JSON.stringify(map, null, 2)}\n`;
}

/**
 * Emit a single ambient `.d.ts` shim covering every discovered route. Import
 * specifiers that consumers write (e.g.
 * `virtual:react-router-next/posts/[postId]`) resolve to a `declare module`
 * block in this file at type-check time.
 */
export function renderDtsShim(
  routeKeys: readonly string[],
  searchSpecifiers?: ReadonlyMap<string, string>,
): string {
  const blocks = routeKeys.map((key) => {
    const id = virtualIdFor(key);
    return `declare module ${JSON.stringify(id)} {
${renderDeclareBody(key, searchSpecifiers?.get(key))}}
`;
  });
  return `${HEADER}
// Ambient declarations for react-router-next virtual route modules.
// Generated by \`react-router-next typegen\` and the reactRouterNext Vite plugin.

declare module "virtual:react-router-next/app-tree" {
  import type { ComponentType } from "react";

  export type RouteModule = {
    default?: ComponentType<{
      params?: Record<string, string | string[] | undefined>;
    }>;
  };

  export const modules: Record<string, RouteModule>;
  export const appDir: string;
}

${blocks.join("\n")}`;
}
