import { routeHasParams } from "./scan";

const HEADER = "// AUTO-GENERATED by react-router-next — do not edit.";

/**
 * Source emitted into the **runtime** virtual module for a given route key.
 * Plain JavaScript — type info lives in the ambient `.d.ts` shim emitted by
 * `renderDtsShim`. Virtual modules aren't transformed as TypeScript by Vite,
 * so the runtime form must not contain type-only syntax.
 */
export function renderRuntimeModule(routeKey: string): string {
  if (!routeHasParams(routeKey)) {
    return `${HEADER}
import { generate as generateBase } from "@evolonix/react-router-next";

const PATH = ${JSON.stringify(routeKey)};

export function generate() {
  return generateBase(PATH, {});
}
`;
  }

  return `${HEADER}
import {
  generate as generateBase,
  useRouteParams as useRouteParamsBase,
} from "@evolonix/react-router-next";

const PATH = ${JSON.stringify(routeKey)};

export function useRouteParams() {
  return useRouteParamsBase(PATH);
}

export function generate(params) {
  return generateBase(PATH, params);
}
`;
}

/**
 * Body of a `declare module 'virtual:react-router-next/<route-key>' { ... }`
 * block. Same shape as the runtime module, but with type-only declarations so
 * `tsc` and editors resolve consumer imports without spinning up Vite.
 */
function renderDeclareBody(routeKey: string): string {
  if (!routeHasParams(routeKey)) {
    return `  import type { RouteParams as RouteParamsBase } from "@evolonix/react-router-next";
  const PATH: ${JSON.stringify(routeKey)};
  export type RouteParams = RouteParamsBase<typeof PATH>;
  export function generate(): string;
`;
  }
  return `  import type { RouteParams as RouteParamsBase } from "@evolonix/react-router-next";
  const PATH: ${JSON.stringify(routeKey)};
  export type RouteParams = RouteParamsBase<typeof PATH>;
  export type RouteProps = { params: RouteParams };
  export function useRouteParams(): RouteParams;
  export function generate(params: RouteParams): string;
`;
}

export function virtualIdFor(routeKey: string): string {
  return `virtual:react-router-next/${routeKey === "" ? "_root" : routeKey}`;
}

export type AppTreeEntry = {
  /** Import specifier emitted for this route file — already resolved relative
   *  to the codegen output directory (e.g. "../../src/app/page.tsx"). */
  importSpecifier: string;
  /** Object key in the emitted `modules` map — root-relative, matching the
   *  shape the Vite plugin produces (e.g. "/src/app/page.tsx"). */
  moduleKey: string;
};

/**
 * Source emitted for the codegen replacement of
 * `virtual:react-router-next/app-tree`. Statically imports every route file so
 * any bundler (webpack/Rspack/Rollup/esbuild) can resolve it — no
 * `import.meta.glob` dependency.
 */
export function renderAppTreeModule(opts: {
  appDirRootRelative: string;
  entries: readonly AppTreeEntry[];
}): string {
  const { appDirRootRelative, entries } = opts;
  const imports = entries
    .map(
      (entry, i) =>
        `import * as m${i} from ${JSON.stringify(entry.importSpecifier)};`,
    )
    .join("\n");
  const mapEntries = entries
    .map((entry, i) => `  [${JSON.stringify(entry.moduleKey)}]: m${i},`)
    .join("\n");
  return `${HEADER}
${imports}

export const modules = {
${mapEntries}
};
export const appDir = ${JSON.stringify(appDirRootRelative)};
`;
}

/**
 * Webpack/Rspack-shaped `resolve.alias` map that routes
 * `virtual:react-router-next/...` requests to the codegen output. The `$`
 * suffix on the app-tree key is webpack's "exact match only" marker, so
 * `virtual:react-router-next/app-tree` resolves to `app-tree.js` and every
 * other `virtual:react-router-next/<key>` falls through to the prefix alias.
 */
export function renderAliasMap(opts: { outDir: string }): string {
  const map = {
    "virtual:react-router-next/app-tree$": `${opts.outDir}/app-tree.js`,
    "virtual:react-router-next": `${opts.outDir}/routes`,
  };
  return `${JSON.stringify(map, null, 2)}\n`;
}

/**
 * Emit a single ambient `.d.ts` shim covering every discovered route. Import
 * specifiers that consumers write (e.g.
 * `virtual:react-router-next/posts/[postId]`) resolve to a `declare module`
 * block in this file at type-check time.
 */
export function renderDtsShim(routeKeys: readonly string[]): string {
  const blocks = routeKeys.map((key) => {
    const id = virtualIdFor(key);
    return `declare module ${JSON.stringify(id)} {
${renderDeclareBody(key)}}
`;
  });
  return `${HEADER}
// Ambient declarations for react-router-next virtual route modules.
// Generated by \`react-router-next typegen\` and the reactRouterNext Vite plugin.

declare module "virtual:react-router-next/app-tree" {
  import type { ComponentType } from "react";

  export type RouteModule = {
    default?: ComponentType<{
      params?: Record<string, string | string[] | undefined>;
    }>;
  };

  export const modules: Record<string, RouteModule>;
  export const appDir: string;
}

${blocks.join("\n")}`;
}
